-- 코드를 입력하세요
SELECT 
    T2.TITLE,
    T1.BOARD_ID,
    T1.REPLY_ID,
    T1.WRITER_ID,
    T1.CONTENTS,
    DATE_FORMAT(T1.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY T1
JOIN USED_GOODS_BOARD T2 ON T1.BOARD_ID = T2.BOARD_ID 
WHERE T2.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY T1.CREATED_DATE, T2.TITLE