-- 코드를 입력하세요
SELECT DISTINCT(T1.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR T1
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2 ON T1.CAR_ID = T2.CAR_ID
WHERE EXTRACT(MONTH FROM START_DATE) IN ('10')
AND CAR_TYPE IN ('세단')
ORDER BY T1.CAR_ID DESC